version: "3"
services:
  web:
    image: klishevich/bp-hapi-react-redux:1.1.0
    environment:
      - "APP_MOCKS=1"
      - "MONGODB_HOST=mongo"
      - "MONGODB_USER=root"
      - "MONGODB_PASS=rootpass"
      - "MONGODB_NAME=admin"
      - "SERVICE_HOST=authotp:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
  mongo:
    image: mongo:3.6.5-jessie
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=rootpass"
    volumes:
      - "/Users/mike/data/mongo:/data/db"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
  authotp:
    image: klishevich/bp-auth-otp-api:1.0.0
    environment:
      - "APP_MOCKS=1"
      - "MONGODB_HOST=mongo"
      - "MONGODB_USER=root"
      - "MONGODB_PASS=rootpass"
      - "MONGODB_NAME=admin"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3000:3000"
    networks:
      - webnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - "discovery.type=single-node"
      - "cluster.name=elastic-prod-cluster"
      - "node.name=elastic-prod-main-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    volumes:
      - "/Users/mike/data/esdata1:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - webnet
networks:
  webnet:
